name: Local Config
version: 1.0.0
schema: v1

models:
  - name: Gemini Flash
    provider: gemini
    model: gemini-flash-latest
    apiKey: ${{ secrets.GOOGLE_API_KEY }}
    roles:
      - chat
      - edit
      - apply

  - name: Claude Opus
    provider: anthropic
    model: claude-opus-4-6
    apiKey: ${{ secrets.ANTHROPIC_API_KEY }}
    roles:
      - chat

  - name: Claude Sonnet
    provider: anthropic
    model: claude-sonnet-4-6
    apiKey: ${{ secrets.ANTHROPIC_API_KEY }}
    roles:
      - edit
      - apply
